version: '3.3' 

services:

  postgisdb:
    hostname: postgis
    build:
      #context: ./postgis_11-2.5/alpine
      #context: ./postgis_11-2.5
      context: ./postgis_12-3.0
    environment:
        # THIS IS MADNESS: envs need to be ordered POSTGRES_DB > POSTGRES_USER > POSTGRES_PASSWORD.
        # https://github.com/docker-library/postgres/issues/41#issuecomment-382925263
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data/pgdata
    command: 
      - "postgres"
      - "-c"
      - "max_connections=25"
      - "-c"
      - "shared_buffers=16GB"
      - "-c"
      - "effective_cache_size=48GB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=4"
      - "-c"
      - "effective_io_concurrency=2"
      - "-c"
      - "work_mem=167772kB"
      - "-c"
      - "min_wal_size=2GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=8"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      #- "shared_preload_libraries=pg_partman_bgw, pg_stat_statements, pg_qualstats, pg_stat_kcache, pg_wait_sampling"
      - "shared_preload_libraries=pg_partman_bgw, pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    ports:
      - 5432:5432
    volumes:
      - ${BASE_DIR}/postgresql-${POSTGRES_VERSION}/data:/var/lib/postgresql/data/pgdata
      - type: tmpfs
        target: /tmp
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 80:80
    depends_on:
      - postgisdb
    restart: unless-stopped